/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n3.2.19-6-ge8f91feae7"
#endif /* AVUTIL_FFVERSION_H */
